language: minimal

dist: focal

services:
  - docker

env:
  global:
    - TZ=UTC
    - IMAGE_NAME="danysk/linux-didattica"

before_script:
  - export TAG="$(git describe || git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)$(date +%Y-%m-%d_%H%M)"

script:
  - docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$TAG" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

deploy:
  - provider: script
    script: docker push $IMAGE_NAME:$TAG && docker push $IMAGE_NAME:latest
    on:
      condition: -n "$DOCKER_PASSWORD"
